name: Clone Dockerfile
on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'Dockerfile'
#      - 'index.js'
#      - 'package.json'
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Clone Dockerfile
        run: |
          wget -O Dockerfile https://raw.githubusercontent.com/opendatalab/MinerU/refs/heads/master/docker/global/Dockerfile

      - name: Replace cuda13 to cuda12
        run: sed -i 's|vllm/vllm-openai:[a-zA-Z0-9_.-]*|vllm/vllm-openai:v0.18.1|g' Dockerfile
        
      - name: Delete model download
        run: sed -i '\|RUN /bin/bash -c "mineru-models-download -s huggingface -m all"|d' Dockerfile
        
      - name: Clone for app
        run: cp Dockerfile ./app/Dockerfile
        
      - name: Change base image
        run: sed -i 's|vllm/vllm-openai:[a-zA-Z0-9_.-]*|python:3.10-slim|g' ./app/Dockerfile
         
      - name: Replace core to gradio
        run: sed -i 's/mineru\[core\]/mineru\[gradio\]/g' ./app/Dockerfile

      - name: Add libglib2.0-0 for opencv (fixes libgthread-2.0.so.0 missing)
        run: sed -i 's|libgl1 &&|libgl1 libglib2.0-0 \&\&|g' ./app/Dockerfile
        
#      - name: pre-install pytorch-cpu
#        run: sed -i '16a\RUN python3 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu --no-cache-dir --break-system-packages' ./app/Dockerfile
        
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest mineru dockerfile'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'

